# Site settings
title: Wydarzenia na hackerspace pomorze
tag_text: Hackerspace pomorze - wydarzenia
description: Informacje o wydarzeniach odbywających się na Hackerspace Pomorze
url: "https://wydarzenia.hsp.sh"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
